import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Jane',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234567'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Blueesh - Tennis',
      slug: 'Blueeshlsleeve',
      category: 'Shoes',
      image: '/images/blueesh1.jpg',
      price: 30,
      brand: 'Blueesh',
      rating: 6,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular shoe from Blueesh',
    },
    {
      name: 'PSugar Box',
      slug: 'palaceSugarbox',
      category: 'Gifts',
      image: '/images/boxwoman.jpg',
      price: 230,
      brand: 'PalaceSugar',
      rating: 10,
      numReviews: 10,
      countInStock: 10,
      description:
        'A popular box from Palace Sugar for give to your girlfriend, contains one cherry perfume, hand cream and transparent lip gloss with cherry taste/aroma',
    },
    {
      name: 'PaWs KittyShorts',
      slug: 'PaWsShorts',
      category: 'Clothes',
      image: '/images/paws7.jpg',
      price: 50,
      brand: 'PaWs',
      rating: 5.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Why not buy this lovely kitty ?',
    },
    {
      name: 'Bear Hat',
      slug: 'PaWshat',
      category: 'Accessories',
      image: '/images/paws8.jpg',
      price: 25,
      brand: 'PaWs',
      rating: 2.9,
      numReviews: 10,
      countInStock: 10,
      description: 'Cute bear hat from PaWs',
    },
    {
      name: 'Bear Gloves',
      slug: 'PaWsgloves',
      category: 'Accessories',
      image: '/images/paws6.jpg',
      price: 25,
      brand: 'PaWs',
      rating: 3,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular bear gloves from PaWs',
    },
    {
      name: 'Solemn Dress',
      slug: 'SolemnDress',
      category: 'Clothes',
      image: '/images/Solemn1.jpg',
      price: 100,
      brand: 'Solemn',
      rating: 8,
      numReviews: 30,
      countInStock: 20,
      description: 'Beautiful long sleeve dress for your date',
    },
    {
      name: 'Crocs Unisex',
      slug: 'Solemncrocs',
      category: 'Shoes',
      image: '/images/Solemn2.jpg',
      price: 30,
      brand: 'Solemn',
      rating: 4.4,
      numReviews: 12,
      countInStock: 20,
      description: 'A popular crocs',
    },
    {
      name: 'Blueesh - Long Sleeve Shirt',
      slug: 'Blueeshlsleeve',
      category: 'Clothes',
      image: '/images/blueesh2.jpg',
      price: 40,
      brand: 'Blueesh',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular shirt from Blueesh, good for winter',
    },
  ],
}

export default data
