import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name: 'Jane',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234567'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Shirt',
      slug: 'Cold',
      category: 'Shirts',
      image: '/images/cloth/image1.jpg',
      price: 70,
      brand: 'Fluffy',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular',
      isFeatured: true,
      banner: '/images/cloth/image1.jpg',
    },
    {
      name: 'Fluffy Hat',
      slug: 'Hat',
      category: 'Accessories',
      image: '/images/cloth/image6.jpg',
      price: 80,
      brand: 'Bear',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular hat',
      isFeatured: true,
      banner: '/images/cloth/image6.jpg',
    },
    {
      name: 'Dress',
      slug: 'slim-dress',
      category: 'Dress',
      image: '/images/cloth/image3.jpg',
      price: 120,
      brand: 'Darkly',
      rating: 5.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular dress',
    },
    {
      name: 'TennisBB',
      slug: 'Blue',
      category: 'Shoes',
      image: '/images/cloth/image8.jpg',
      price: 30,
      brand: 'Cute',
      rating: 2.9,
      numReviews: 10,
      countInStock: 10,
      description: 'Cute looking tennis',
    },
    {
      name: 'Bear Gloves',
      slug: 'Bear',
      category: 'Accesories',
      image: '/images/cloth/image2.jpg',
      price: 95,
      brand: 'Bear',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular bear gloves for winter',
    },
    {
      name: 'Shorts',
      slug: 'classic-shorts',
      category: 'Shorts',
      image: '/images/cloth/image4.jpg',
      price: 75,
      brand: 'Cute',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular short',
    },
    {
      name: 'Crocs',
      slug: 'classic-crocs',
      category: 'Shoes',
      image: '/images/cloth/image5.jpg',
      price: 70,
      brand: 'Cute',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular crocs',
    },
    {
      name: 'Long Sleeve Shirt',
      slug: 'cold-classic-cloth',
      category: 'Shirt',
      image: '/images/cloth/image7.jpg',
      price: 90,
      brand: 'Cute',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular shirt for winter',
    },
  ],
}

export default data
